name: Publish

on:
  workflow_run:
    workflows: ["Test Commands"]
    types:
      - completed

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success'  && github.event.workflow_run.head_branch == 'main' }}
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/checkout@v2

      - uses: imjasonh/setup-ko@v0.6
      - run: ko publish --base-import-paths ./cmd/model_downloader -t ${GITHUB_SHA::7}
      - working-directory: ./cmd/dataset_tokenizer
        run: go get github.com/wbrown/gpt_bpe/resources
      - working-directory: ./cmd/dataset_tokenizer
        run: ko publish --base-import-paths . -t ${GITHUB_SHA::7}
